Repository Airmime/minstyle.io, pull requests merged in 2018-12, with the labels that each got.

#11 Update padding for codestyle
  css/scss/_alert.scss
Labels: codestyle

#12 Update zero codestyle
  css/scss/_badge.scss
Labels: codestyle

#13 Update padding codestyle
  css/scss/_blockquote.scss
Labels: codestyle

#14 Update zero codestyle
  css/scss/_button.scss
Labels: codestyle

#15 Add and delete zero
  css/scss/_table.scss
Labels: codestyle

#16 Update zero codestyle
  css/scss/_progressbar.scss
Labels: codestyle

#17 Update padding
  css/scss/_grid.scss
Labels: codestyle

#18 Update zero codestyle
  css/scss/_form.scss
Labels: codestyle

#20 Update padding
  css/scss/_typographie.scss
Labels: codestyle

#21 Delete default extensions
  css/scss/minstyle.io.scss
Labels: codestyle

#10 Replace CDN link with minified CSS file
  README.md
Labels: enhancement

#23 V.0.2.3
  README.md
  bower.json
  css/minstyle.io.css
  css/scss/_alert.scss
  css/scss/_badge.scss
  css/scss/_blockquote.scss
  css/scss/_button.scss
  css/scss/_card.scss
  css/scss/_form.scss
  css/scss/_grid.scss
  css/scss/_progressbar.scss
  css/scss/_table.scss
  css/scss/_typographie.scss
  css/scss/minstyle.io.scss
  examples/alert.html
  examples/badge.html
  examples/blockquote.html
  examples/box.html
  examples/button.html
  examples/card.html
  examples/css/prism.css
  examples/css/style.css
  examples/form.html
  examples/grid.html
  examples/heading.html
  examples/img/favicon.ico
  examples/img/gradient-logo.png
  examples/img/logo.png
  examples/js/prism.js
  examples/list.html
  examples/menu.html
  examples/progressbar.html
  examples/table.html
  examples/typographie.html
  index.html
  package.json
Labels: codestyle, enhancement
